project:
  type: website
  output-dir: docs

website:
  title: "QR2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus & policies


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



