---
title: "QR2 Winter 2025"
subtitle: "Course homepage"
---



::: {.callout-note}
## Shared homepage

There are six sections of QR2 offered in the Winter 2025 term, taught by five different instructors. This page is a **shared** homepage for the course. To explain ... the QR2 course has been constructed by the instructors and reflects our consensus vision of how best to achieve institution-wide objectives of core courses.

It's impractical (and probably not optimal) for all the sections to be exactly identical. Different sections meet on different days and instructors are most effective when teaching in their individual styles.

On a day-to-day basis, you should *refer to your instructor's schedule* linked to below.
:::


## Day-by-day schedule

There are six class sections for QR2. These follow a similar schedule, but naturally the viscisitudes and opportunities of classroom discussion lead to variation on a section-by-section basis. Accordingly, you should *bookmark* your section in your browser for easy access to the most up-to-date information.

- [Section 1 (Prof. Ruth)](day-by-day/Ruth-schedule.html)
- [Section 2 (Prof. Kolpakov)](day-by-day/Kolpakov-schedule.html)
- [Section 3 (Prof. Kolpakov)](day-by-day/Kolpakov-schedule.html)
- [Section 4 (Prof. Puelz)](https://github.com/dpuelz/Quantitative-Reasoning-II)
- [Section 5 (Prof. Overbey)](https://github.com/eliah-o/Quantitative-Reasoning-II)
- [Section 6 (Prof. Kaplan)](day-by-day/Kaplan-schedule.html)



## General information

Textbooks:

1. David Spiegelhalter, *The Art of Statistics: Learning from Data*
2. Hans Rossling, *Factfulness*
3. QR 2 *Computing Tutorials* [free and online](https://dtkaplan.github.io/QR2-computing/)

Computing:

Our data-science computing platform is embedded into each course document that involves computing. You do not need to install any special software; just an up-to-date web browser will do. No previous experience with technical software is required. For those interested in such things, the underlying platform is R along with the `dplyr` data-wrangling system, products that are extensively used professionally in data science. 

Policies: [See the syllabus page](syllabus.html)

Much of the required course work---reading questions, computing activities and exercises, and so on---is arranged for easy electronic submission. The uploading file uses your `@uaustin.org` email address. 
