---
title: "Reading Questions"
---

{{< include start-up.qmd >}}

::: {.callout-warning}
## For instructors only

This document is intended for instructors as they create their day-to-day schedules. Those schedules will provide the student-facing link to reading-question documents.
:::

Each of the six blocks in QR2 has assigned readings from Spiegelhalter, Rossling, and the computing tutorials. There are corresponding reading questions. These are organized by book chapter. Your instructor will indicate which questions are due and when.

Some of the reading questions should be completed and submitted *before* the date scheduled for the classroom discussion. Others are intended as *follow up* after the discussion. Due dates for the follow-up questions will be specified by individual instructors. 

Note that some documents may be empty.

## Block 1: Data, visualization, trends

- `r reading_links("S", 0)`
- `r reading_links("S", 1)`
- `r reading_links("R", 1)`
- `r reading_links("R", 2)`
- `r tutorial_link(1)`


## Block 2: Prediction

- `r reading_links("S", 3)`
- `r reading_links("S", 6)`
- `r reading_links("R", 4)`
- `r reading_links("R", 5)`
- `r tutorial_link(2)`

## Block 3: Regression and Adjustment

- `r reading_links("S", 5)`
- `r reading_links("R", 3)`
- `r tutorial_link(3)`

## Block 4: Precision

- `r reading_links("S", 8)`
- `r reading_links("S", 9)`
- `r reading_links("R", 6)`
- `r reading_links("R", 7)`
- `r tutorial_link(4)`

## Block 5: Confounding, accuracy, and adjustment

- `r reading_links("S", 4)`
- `r reading_links("R", 8)`
- `r reading_links("R", 9)`
- `r tutorial_link(5)`

## Block 6: Hypothetical reasoning

- `r reading_links("S", 11)`
- `r reading_links("S", 13)`
- `r reading_links("S", 14)`
- `r reading_links("R", 10)`
- `r tutorial_link(6)`

