---
title: "QR2 Prof. Kolpakov's Section"
subtitle: "Day-by-day schedule, readings, and notes"
---

{{< include ../start-up.qmd >}}

## Near future

::: {.callout-note}
## 13. Wednesday 19 February

Course Project

- We shall be working towards understanding the problem and formulating Sprint 2
- Assignments due: Report on Sprint 1 (on Github)

:::

::: {.callout-note}
## 14. Thursday 20 February

Block 5 Accuracy, confounding and adjustment 

- We shall talk about accuracy vs precision `r tutorial_link(5)`
- We shall understand what confounding is, and how to adjust for it
- Assignments due:
  - [Computing Activities for Tutorial 4](https://dtkaplan.github.io/QR2-computing/exercises-4.html) 
  
:::


## Further out (i.e. tentative)


::: {.callout-note}
## 15. Monday 24 February

Course Project

- What is accuracy and precision as applied to your project?
- What about possible confounders? 
- Sprint 2 starts (on Github)

:::


::: {.callout-note}
## 16. Thursday 27 February

Block 5 Accuracy, confounding and adjustment (continued)

- Assignments due:
  - [Computing Activities for Tutorial 5](https://dtkaplan.github.io/QR2-computing/exercises-5.html) 

:::


::: {.callout-note}
## 17. Monday 3 March
Block 6 Hypothetical reasoning & Bayes

- Bayesian approach: prior and posterior probabilities. 
- We shall talk about hypothesis testing. 
- New readings:
  - Start `r tutorial_link(6)`

:::


::: {.callout-note}
## 18. Thursday 6 March

Block 6 Hypothetical reasoning & Bayes (continued)

- New readings 
  - Spiegelhalter Chap 10
- We continue discussing hypothesis testing
- Which hypotheses can you formulate and test in your project? 
- Assignments due:
  - Report on Sprint 2 (on Github)


:::


::: {.callout-note}
## 19. Monday 11 March

Block 6 Hypothetical reasoning & Bayes (continued)

- New readings:
  - Spiegelhalter Chap 11
- Discussion of Bayesian approach and its applications
- Can you make use of it in your project? 
- Sprint 3 starts

:::


::: {.callout-note}
## 20. Thursday 13 March

- New readings:
  - Spiegelhalter Chap 12 and Chap 13
- We will discuss the reproducibility crisis in sciences
- Assignments due:   
  - [Computing Activities for Tutorial 6](https://dtkaplan.github.io/QR2-computing/exercises-6.html) 

:::


::: {.callout-note}
## 21. Monday 17 March

Course Project

- Assignments due:
  - Sprint 3 report (on Github)

:::

::: {.callout-note}
## 20. Thursday 20 March

Course Project 

- Final project presentation

:::


## Already past

::: {.callout-note}
## 11. Monday 10 February - Monday 17 February

Reading break 

- No classes will be held
- Work on the dataset you picked, try getting some familiarity with it
- Work on Sprint 1 (on Github)

:::

::: {.callout-note}
## 10. Thursday 6 February

Course Project 

- We shall start some Course Project preparations: accessing the dataset, merging its parts together, trying to get some basic information from it (over the reading break)

- Sprint 1 starts (on GitHub)

- Assignments due:
  - [Computing Activities for Tutorial 3](https://dtkaplan.github.io/QR2-computing/exercises-3.html) 

:::

::: {.callout-note}
## 9. Monday 3 February

Block 4 Precision & Confidence

- We shall discuss confidence intervals (see notes on Populi)
- We shall talk about regression coefficients `r tutorial_link(4)`

:::

::: {.callout-note}
## 8. Thursday 30 January

Block 3 Regression & Adjustment (continued)

- New readings  
    - Start `r tutorial_link(4)`

:::

::: {.callout-note}
## 7. Monday 27 January, 2025

Block 3: Regression & Adjustment

- New readings
    - Spiegelhalter Chap 5 & [reading questions](../questions/S5-before.html)
    - Rosling Chap 3 & [reading questions](../questions/R3-before.html)
    - Start `r tutorial_link(3)`

:::

::: {.callout-note}
## 6. Thursday 23 January
Block 2: Prediction (continued)

- New readings:
  - Quantifying Uncertainty of Populi (Sections 3 and 4)
  
- Assignments due:
  - Please be sure to complete  [Computing Activities for Tutorial 2](https://dtkaplan.github.io/QR2-computing/exercises-2.html).
:::


::: {.callout-note}
## 5. Wednesday 22 January, 2025
Block 2: Prediction (continued)

- New readings:
  a. Quantifying Uncertainty of Populi (Sections 1 and 2)
  b. Start `r tutorial_link(2)`
:::


::: {.callout-note}
##  Monday 20 January, 2025

MLK Observance (will hold class on Wednesday, January 22)

:::

::: {.callout-note}
## 4. Thursday 16 January

Block 2: Prediction

- New readings    
    a. Rosling Chap 4 & [reading questions](../questions/R4-before.html). We're skipping Rosling 3, saving that for another day.
    b. Spiegelhalter Chap 3 & [reading questions](../questions/S3-before.html)

- Assignments due:
    - Please be sure to complete [Computing Activities for Tutorial 1.](https://dtkaplan.github.io/QR2-computing/exercises-1.html)

:::


::: {.callout-note}
## 3. Monday 13 January, 2025

Block 1 (continued)

- New readings:
    a. `r tutorial_link(1)`
    b. Rosling Chap 2 [questions](../questions/R2-before.html)

- Assignments due before class time: 
    - Remember that the "New readings" section has links to the relevant reading questions. 
    - For the computing tutorials, there are no "questions" as such, but be sure to run and, better, play around with the Active R Chunks. Then go through the familiar "Collect answers" and submission process. Your "answers" will be the contents of the Active R Chunks that you have run. 
    - These principles apply to all class sessions, but won't be restated explicitly in other day's itemizations.


- Discussions and Activities
    i. Rosling reading
    ii. Review of Computing Tutorial 1
    iii. In-class group work on computing activities

:::


::: {.callout-note}
## 2. Thursday 9 January

Block 1: Data, visualization, trends

- New readings:
    a. Spiegelhalter Chap 1 [questions](../questions/S1-before.html)
    b. Rosling Chap 1 [questions](../questions/R1-before.html)

- Assignments due before class time:
    i.  Before-class reading questions as linked above.
    ii. Spiegelhalter introduction [follow-up reading questions](../questions/S0-after.html)

- Discussions:
    - Sorting out any start-up problems
    - Spiegelhalter and Rosling readings
    - In-class orientation to computing
:::


::: {.callout-note}
## 1. Monday 6 January, 2025

Orientation to QR2

- Readings:
    - Spiegelhalter Introduction
    - Rosling Introduction
    - Note: As a rule, you should do preparatory reading *before* class. For the first days of class, we shall make an exception, and probably discuss a few things on the tangent, too. 

- Discussion:
    - Learning about data and statistics
    - Spiegelhalter Introduction
    - Rosling Introduction
    - Note: The items under the "Discussion" header in this document are just FYI. The readings and the reading questions are the appropriate preparation.

- Computing:
    - Please have your laptops with you! There will be a few *in-class* computing exercises.
    - The main computing tool for this class is R. You do not need to install it on your computer, although you definitely may.  
:::




