---
title: "Kaplan's in-class notes for 2025-01-14"
date: 2025-01-14
---




## Graphics background

Tell me what types of statistical graphics you've encountered. Draw some (imagined) examples of different types on the board.

--------

We will mainly work with one type: the "annotated point plot."

General statistical graphics words: 
- graphics frame
- glyphs
- graphical property ("aesthetic"): color, transparency, angle, length, size, ...
- scale: transformation from data values to graphical property, E.G. or y or color or size or whatever 
- "guide" the tick marks or legend.
- facet

`point_plot()` system:

- points and annotations
- a `point_plot()` is fundamentally about a data frame and the trends encountered therein.
    - each point corresponds to **one** specimen from the data frame.
    - point plots work with either quantitative or categorical variables
    - a point is a simple glyph with location (x, y, facet) and color, transparency (`point_ink`).
- an "annotation" is another kind of glyph, typically with somewhat complex structure
    - we will use two basic types of annotations, `"model"` and `"violin"`. They serve different purposes.
    - annotations reflect **collective** properties of multiple specimens (often *all* the specimens)
    
Try out different variables.
```{webr-r}
names(Penguins)
Penguins |>
  point_plot()
```

Show different scales: categorical and quantitative

Add violin annotations.

Add model annotations.

The meaning of `var ~ 1`. We'll call this the Null model.

`point_ink`, `model_ink` annotations. (Explain the use of `_` instead of `-` within a name.)



## Rossling Chapter 2

Show some answers to the reading questions

## Wrangling

You are expected to learn the names of the basic operations but not to be able to create complex "queries" with them. Such mastery comes with experience.

Talk about units of observation. Show how summarize changes the unit of observation, but the other wrangling functions leave it alone.

The basic operations.



The most advanced wrangling operation is a "join" or "merge". This is the only wrangling operation that takes two data frames as input. [Try `Grades`, `Sessions`, `Gradepoint` database.]

- You do not need to master *joins*. But it is essential to work with databases. As of 10 years ago, few people other than database professionals knew about it: I taught it to hundreds of faculty, most of whom were shocked that something so simple accomplished what they had been doing by hand and calling "cross referencing."

## Interpreting trends

`Births78` shows a pattern, a kind of trend
