---
title: "Kaplan's in-class notes for 2025-01-21"
date: 2025-01-21
---



```{r include=FALSE}
library(LSTbook)
```



## Demonstrate construction of a classification tree



```{webr-r}
Birdkeepers |>
  point_plot(LC ~ BK, annot = "model")
```

Risk and risk ratio

```{webr-r}
Birdkeepers |>
  summarize(total = n(), 
            nC = sum(LC == "LungCancer"), 
            probC = mean(LC == "LungCancer"), 
            .by = BK)
```

Risk ratio: 0.50 / 0.20 = 2.5. Birdkeeping is a "risk factor" for lung cancer.

Construct a one-node classification tree of lung cancer versus bird-keeping.

Construct the confusion matrix. False-positives and negatives, sensitivity, specificity, ~~accuracy~~ 

- Build a one-node classification tree based on `YR`. Meaning of the threshold. Receiver operating curve. 



```{webr-r}
Birdkeepers |>
  point_plot(LC ~ YR + 1 + BK, annot = "model")
```


## Spiegelhalter Ch 6

Let's be careful about language, especially "true"

> The confusion matrix is essentially the data your algorithm incorrectly
predicts.

> A confusion matrix is a table that classifies identification functions in machine learning.

> Sensitivity is what is true that your algorithm also gets right, while the
specificity is what is not true that your algorithm gets right.


## Work with the start of Tutorial 2

`model_train()` and `model_eval()`. 

Prediction interval

Use an example with a binary response variable.

## Quiz
