---
title: "Kaplan's in-class notes for 2025-02-21"
date: 2025-02-21
---

```{r include=FALSE}
library(LSTbook)
library(ggformula)
library(dplyr)
```

Here is the raw bowel-cancer data from Spiegelhalter Fig. 9.2
```{r}
Bowel_cancer_UK <- 
  suppressMessages(readr::read_csv("09-2-bowel-cancer-data-x.csv", )) |>
  mutate(rate_per_100000 = (n/d)*100000)
Bowel_cancer_UK |> nrow()
Bowel_cancer_UK |> head()
me <- function(pop, multiplier = 1.96) { 
  multiplier* 100000*sqrt(0.000176*(1-0.000176)/pop)
}
curves <- tibble::tibble(
  pop = 10^seq(4.5, 6.2, length=200),
  t95 = 17.6 + me(pop, 1.96),
  b95 = 17.6 - me(pop, 1.96),
  t99 = 17.6 + me(pop, 2.58),
  b99 = 17.6 - me(pop, 2.58),
)
Bowel_cancer_UK |>
  gf_point(rate_per_100000 ~ d) |>
  gf_ribbon(t99 + b99 ~ pop, data = curves, 
            fill = "blue", alpha = 0.1, inherit=FALSE) |>
  gf_ribbon(t95 + b95 ~ pop, data = curves, 
            fill = "green", alpha = 0.2, inherit=FALSE)
```


## Simulation of funnel plot

```{r}
BCsim <- datasim_make(
  popsize <- round(10^seq(4.5, 6.1, length = n)),
  rate <- 100000*rbinom(n, popsize, prob = 0.000176) / popsize
)
BCsim |> take_sample(10000) |>
  gf_point(rate ~ popsize, alpha = 0.1, size = .5) |>
  gf_ribbon(t99 + b99 ~ pop, data = curves, 
            fill = "blue", alpha = 0.1, inherit=FALSE) |>
  gf_ribbon(t95 + b95 ~ pop, data = curves, 
            fill = "green", alpha = 0.2, inherit=FALSE)
```

## Simulation

Make a system with known coefficients and different amounts of randomness.

```{r}
height_sim <- datasim_make(
  mom <- rnorm(n, mean=62, sd=3),
  dad <- rnorm(n, mean=66, sd=3.5),
  sex <- categorical(n, F=1, M=1 ),
  kid <- 15 + 0.35*mom + 0.40*dad + 
    cat2value(sex, F=0, M=5) + 
    rnorm(n, sd=3.4)
)
take_sample(height_sim, n=400) |>
  model_train(kid ~ mom + dad + sex) |>
  conf_interval() |>
  trials(10) |>
  summarize(m = mean(.coef), v = var(.coef), .by = term)

```
## Take new random samples from a big set


## Resample


## Just rely on `model_train()` and `conf_interval()`

